# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: caa496d7c2a3535c8e0cc4da7f2097a66565b2737ebe9524722e886236459bc3a6fb1328ac5ea4b09e1f37e79150c447367f2b93cb8ebec422320036bf49cd14

test:
  secret_key_base: 95b4a63b8e6e0da4617148acc676020ada691fc3b67d9236a64a3892f3ec4ff79d1be9585733b4112097078613c5007c2371687cd794a14dd3422e11c81f935c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
